favicon:
  mimetype: image/png
  path: 'public://favicon.png'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  name: true
  node_user_picture: true
  slogan: true
logo:
  path: 'public://logo.png'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
