_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  ajax_login_popup: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  ckeditor5: 0
  ckeditor_colorbox_inline: 0
  colorbox: 0
  colorbox_inline: 0
  comment: 0
  config: 0
  contact: 0
  content_sync: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  examples: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  highlight_js: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_draggable: 0
  jquery_ui_effects: 0
  jquery_ui_resizable: 0
  jwt: 0
  jwt_auth_issuer: 0
  jwt_path_auth: 0
  key: 0
  libraries: 0
  link: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  mimemail: 0
  mmoda: 0
  mmoda_antares: 0
  mmoda_crbeam: 0
  mmoda_cta: 0
  mmoda_desi: 0
  mmoda_gw: 0
  mmoda_hess: 0
  mmoda_icecube: 0
  mmoda_integral: 0
  mmoda_isgri: 0
  mmoda_jemx: 0
  mmoda_legacysurvey: 0
  mmoda_magic: 0
  mmoda_sgwb: 0
  mmoda_spi_acs: 0
  mysql: 0
  node: 0
  openid_connect: 0
  options: 0
  page_cache: 0
  page_example: 0
  pager_example: 0
  path: 0
  path_alias: 0
  phpass: 0
  remove_unused_files: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_attachment: 0
  webform_devel: 0
  webform_options_custom: 0
  webform_scheduled_email: 0
  webform_schema: 0
  webform_ui: 0
  pathauto: 1
  externalauth: 10
  views: 10
  standard: 1000
  eu_cookie_compliance: 1001
theme:
  olivero: 0
  claro: 0
  stark: 0
  stable9: 0
  bootstrap5: 0
  mmoda_bootstrap: 0
profile: standard
