copy_enable: 0
copy_bg_transparent: 0
copy_bg_color: '#4caf50'
copy_txt_color: '#ffffff'
copy_btn_text: ''
copy_success_text: ''
success_txt_color: '#4caf50'
role_copy_access:
  anonymous: 0
  authenticated: 0
  administrator: 0
  content_editor: 0
  user_manager: 0
  content_manager: 0
  general: 0
  integral_private_qla: 0
  magic: 0
  unige_hpc_full: 0
  public_pool_hpc: 0
  antares: 0
  sdss: 0
  apc: 0
  bitp: 0
  renku_contributor: 0
  gallery_contributor: 0
  job_manager: 0
  developer: 0
languages:
  c: c
  css: css
  java: java
  javascript: javascript
  php: php
  perl: perl
  python: python
  profile: profile
  python-repl: python-repl
  1c: 0
  4d: 0
  'sap-abap, abap': 0
  abnf: 0
  accesslog: 0
  ada: 0
  apex: 0
  arduino: 0
  armasm: 0
  avrasm: 0
  actionscript: 0
  alan: 0
  ln: 0
  angelscript: 0
  apache: 0
  applescript: 0
  arcade: 0
  asciidoc: 0
  aspectj: 0
  autohotkey: 0
  autoit: 0
  awk: 0
  'ballerina, bal': 0
  'bash, sh, zsh': 0
  basic: 0
  bbcode: 0
  blade: 0
  bnf: 0
  bqn: 0
  brainfuck: 0
  csharp: 0
  cpp: 0
  cal: 0
  c3: 0
  cos: 0
  candid: 0
  cmake: 0
  cobol: 0
  codeowners: 0
  coq: 0
  csp: 0
  capnproto: 0
  chaos: 0
  chapel: 0
  cisco: 0
  clojure: 0
  coffeescript: 0
  cpc: 0
  crmsh: 0
  crystal: 0
  curl: 0
  cypher: 0
  d: 0
  dafny: 0
  dart: 0
  dpr: 0
  diff: 0
  django: 0
  dns: 0
  dockerfile: 0
  dos: 0
  dsconfig: 0
  dts: 0
  dust: 0
  dylan: 0
  ebnf: 0
  elixir: 0
  elm: 0
  erlang: 0
  excel: 0
  extempore: 0
  fsharp: 0
  fix: 0
  flix: 0
  fortran: 0
  func: 0
  gcode: 0
  gams: 0
  gauss: 0
  godot: 0
  gherkin: 0
  hbs: 0
  gn: 0
  go: 0
  gf: 0
  golo: 0
  gradle: 0
  graphql: 0
  groovy: 0
  gsql: 0
  xml: 0
  http: 0
  https: 0
  haml: 0
  handlebars: 0
  haskell: 0
  haxe: 0
  hlsl: 0
  hy: 0
  ini: 0
  inform7: 0
  irpf90: 0
  iptables: 0
  json: 0
  jolie: 0
  julia: 0
  julia-repl: 0
  kotlin: 0
  tex: 0
  leaf: 0
  lean: 0
  lasso: 0
  less: 0
  ldif: 0
  lisp: 0
  livecodeserver: 0
  livescript: 0
  lookml: 0
  lua: 0
  luau: 0
  macaulay2: 0
  makefile: 0
  markdown: 0
  mathematica: 0
  matlab: 0
  maxima: 0
  mel: 0
  mercury: 0
  mips: 0
  mint: 0
  mirc: 0
  mizar: 0
  mkb: 0
  mlir: 0
  mojolicious: 0
  monkey: 0
  moonscript: 0
  motoko: 0
  n1ql: 0
  nsis: 0
  never: 0
  nginx: 0
  nim: 0
  nix: 0
  oak: 0
  ocl: 0
  ocaml: 0
  objectivec: 0
  glsl: 0
  openscad: 0
  ruleslanguage: 0
  oxygene: 0
  pf: 0
  papyrus: 0
  parser3: 0
  pine: 0
  plaintext: 0
  pony: 0
  pgsql: 0
  powershell: 0
  processing: 0
  prolog: 0
  properties: 0
  proto: 0
  puppet: 0
  qsharp: 0
  k: 0
  qml: 0
  r: 0
  cshtml: 0
  reasonml: 0
  redbol: 0
  rib: 0
  rsl: 0
  rescript: 0
  risc: 0
  riscv: 0
  graph: 0
  robot: 0
  rpm-specfile: 0
  ruby: 0
  rust: 0
  rvt: 0
  SAS: 0
  scss: 0
  sql: 0
  p21: 0
  scala: 0
  scheme: 0
  scilab: 0
  sfz: 0
  shexc: 0
  shell: 0
  smali: 0
  smalltalk: 0
  sml: 0
  solidity: 0
  spl: 0
  'stan, stanfuncs': 0
  stata: 0
  iecst: 0
  stylus: 0
  subunit: 0
  supercollider: 0
  svelte: 0
  swift: 0
  'tcl, tk': 0
  terraform: 0
  tap: 0
  thrift: 0
  toit: 0
  tp: 0
  tsql: 0
  twig: 0
  typescript: 0
  unicorn-rails-log: 0
  vbnet: 0
  vba: 0
  vbscript: 0
  vhdl: 0
  vala: 0
  verilog: 0
  vim: 0
  xsharp: 0
  axapta: 0
  x86asm: 0
  x86asmatt: 0
  xl: 0
  xquery: 0
  yml: 0
  zenscript: 0
  zephir: 0
  zig: 0
theme: '3024'
