_core:
  default_config_hash: _qiZJYCM9QMoFxzt2G2sgjOQfCL8EzxX1EJn5J4am5Y
name: crbeam
messenger: null
title: Crbeam
enabled: true
product_type: compute_new_column
query_type: Real
radius: 2
weight: 80
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/crbeam
acknowledgement: |
  Service provided by <a href="https://github.com/oda-hub" target="_blank">MMODA</a>
