_core:
  default_config_hash: l8O9FIZ4G2_LXmjbVxJWHMJ5jTCuerbn3qFj9PZDZqY
name: legacysurvey
messenger: IR/Visible
title: 'DESI LegacySurvey'
enabled: true
product_type: legacy_survey_image
data_release: 9
radius_photometry: 1.0
image_band: g
image_size: 3.0
pixel_size: 1
query_type: Real
weight: 100
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/legacy-survey
acknowledgement: |
  If this result is used for publicaiton, please cite <a href="https://doi.org/10.5281/zenodo.6376844" target="_blank">https://doi.org/10.5281/zenodo.6376844</a> and include an acknowledgement of the Legacy Survey: <a href="https://www.legacysurvey.org/acknowledgment/" target="_blank">https://www.legacysurvey.org/acknowledgment/</a>
