_core:
  default_config_hash: T6yQjub__0kQP0vn2dwr3lBcyyk_nMlxRQ4m5y7iTnA
name: hess
messenger: Gamma-rays
title: HESS
enabled: true
weight: 110
product_type: Spectrum
Radius: 2.5
R_s: 0.2
pixsize: 0.05
Emin: 0.1
Emax: 100.0
NEbins: 30
NTbins: 30
Efit_min: 0.2
Efit_max: 10.0
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/hess
acknowledgement: |
  'Service provided by <a href="https://github.com/oda-hub" target="_blank">MMODA</a>',
enable_use_catalog: false
allowed_roles: developer
