_core:
  default_config_hash: mjVs3KkhasVOxrEJKUAt1Ees-0w9APu5KzWoQxnDHxY
name: sgwb
messenger: 'Gravitational Waves'
title: SGWB
enabled: true
query_type: Real
weight: 130
product_type: Phase_transition_parameters
epsilon_turb: 1.0
T_star: 0.178
g_star: 20
alpha: 1.0
beta_H: 3.3
v_w: 0.999
h: 0.7
acknowledgement: 'Service provided by <a href="https://github.com/oda-hub" target="_blank">MMODA</a>'
enable_use_catalog: false
allowed_roles: developer
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/sgwb
