_core:
  default_config_hash: PdXs2NKNZRFyX5pI9nsrMvjIyF4saCjCJGt4opa3YaU
name: crbeam
messenger: null
title: Crbeam
enabled: true
product_type: compute_new_column
query_type: Real
fn: testfile.tsv
z_start: 0.0
new_column: sum
expression: 'c1 > 1e3'
Npart: 5000
sep: comma
particle_type: gamma
column: c0
Emax: 30.0
weights: c1
Emin: 0.1
binning: logarithmic
EminSource: 1.0
minval: 10000000000.0
Gamma: 2.0
maxval: 10000000000000.0
EGMF_fG: 10.0
nbins: 15
lmaxEGMF_Mpc: 5.0
xlabel: 'Energy, eV'
jet_half_size: 5.0
ylabel: Ncounts
jet_direction: 0.0
window_size_RA: 2.0
psf: 1.0
window_size_DEC: 1.0
livetime: 0.1
EBL: 'Franceschini 2017'
instrument_version: '<a target="_blank" class="text-decoration-none" href="https://gitlab.renkulab.io/astronomy/mmoda/crbeam/-/commit/7e706f92004d0e78fca205a9f039d06856c35497">7e706f92</a>'
weight: 90
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/crbeam
acknowledgement: |
  Service provided by <a href="https://github.com/oda-hub" target="_blank">MMODA</a>
