_core:
  default_config_hash: RzgbG2xxSUzPiivigTPghiFAe2g2EtM4hPl2UljiMTw
name: desi
messenger: null
title: 'DESI Legacy Survey'
enabled: true
query_type: Real
weight: 140
product_type: Catalog
Radius: 1.0
data_release: 9
pixsize: 1.0
band: g
acknowledgement: 'Service provided by <a href="https://github.com/oda-hub" target="_blank">MMODA</a>'
enable_use_catalog: false
allowed_roles: developer
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/desi-legacy-survey
