_core:
  default_config_hash: tbWNx8IiAM5ubaZLsPx8uPiMUgjz6yfxNPJSFBdPKl0
name: icecube
messenger: Neutrino
title: Icecube
enabled: true
query_type: Real
weight: 120
product_type: Spectrum
IC40: 0
Slope: 3.0
IC59: 0
IC79: 0
IC86_I: 1
IC86_II_VII: 1
Spectrum_type: Free_slope
Radius: 1.0
pixel_size: 0.5
TSmap_type: Fixed_slope
acknowledgement: 'Service provided by <a href="https://github.com/oda-hub" target="_blank">MMODA</a>'
enable_use_catalog: false
allowed_roles: developer
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/icecube
