_core:
  default_config_hash: N0eULfLfLAu8f9dsqh0UlE7hSsq2iZGSgirnB_5cMGk
name: spi_acs
messenger: Gamma-rays
title: 'INTEGRAL SPI-ACS'
enabled: true
product_type: spi_acs_lc
query_type: Real
time_bin: 2
weight: 50
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/integral-spi-acs
acknowledgement: |
  If you use results or material from this instrument in our application, MMODA, do not forget to quote our paper: <br> <a href="https://arxiv.org/abs/2002.12895" target="_blank">A. Neronov, V. Savchenko, A. Tramacere, M. Meharga, C. Ferrigno, S.Paltani <br> An online data analysis system of INTEGRAL telescope</a>
