_core:
  default_config_hash: 49UDck47UOw_9rJOGnGsGlU_K6Lx4MmX_PqxSNkr8QI
name: jemx
messenger: X-rays
title: 'INTEGRAL JEM-X'
enabled: true
osa_version: OSA11.2
radius: 4
scw_list: '005100410010.001,005100420010.001'
max_pointings: 50
integral_data_rights: public
E1_keV: 3.0
E2_keV: 20.0
query_type: Real
detection_threshold: 7.0
product_type: jemx_image
time_bin: 1000
time_bin_format: sec
weight: 20
help_page_url: help/mmoda/integral-jem-x
acknowledgement: |
  If you use results or material from this instrument in our application, MMODA, do not forget to quote our paper: <br> <a href="https://arxiv.org/abs/2002.12895" target="_blank">A. Neronov, V. Savchenko, A. Tramacere, M. Meharga, C. Ferrigno, S.Paltani <br> An online data analysis system of INTEGRAL telescope</a>
