_core:
  default_config_hash: 3DhTxqEUbVzdurqtPwt1w85a82hjreEsbQIlg5kGXuM
name: isgri
messenger: 'Hard X-rays'
title: 'INTEGRAL ISGRI'
enabled: true
osa_version: OSA11.2
radius: 15
scw_list: '005100410010.001,005100420010.001'
max_pointings: 50
integral_data_rights: public
E1_keV: 28.0
E2_keV: 40.0
query_type: Dummy
detection_threshold: 7.0
product_type: isgri_image
time_bin: 1000
time_bin_format: sec
weight: 10
enable_use_catalog: true
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/integral-isgri
acknowledgement: |
  If you use results or material from this instrument in our application, MMODA, do not forget to quote our paper: <br> <a href="https://arxiv.org/abs/2002.12895" target="_blank">A. Neronov, V. Savchenko, A. Tramacere, M. Meharga, C. Ferrigno, S.Paltani <br> An online data analysis system of INTEGRAL telescope</a>
