_core:
  default_config_hash: 0rBKJ9qj768f6j0ZfVHzS0f7LAqUGUHKcRhNrNC6nFg
name: desi
messenger: null
title: 'DESI Legacy Survey'
enabled: true
query_type: Real
weight: 140
product_type: Catalog
Radius: 1.0
data_release: 9
pixsize: 1.0
band: g
acknowledgement: 'Service provided by <a href="https://github.com/oda-hub" target="_blank">MMODA</a>'
enable_use_catalog: false
allowed_roles: developer
instrument_version: '<a target="_blank" class="text-decoration-none" href="https://gitlab.renkulab.io/astronomy/mmoda/desi-legacy-survey/-/commit/5b8db9308dae4983d32dda76d0b2f7be45970f30">5b8db930</a>'
data_server_url: dispatch-data/run_analysis
help_page_url: help/mmoda/desi-legacy-survey
