settings:
  type: config_object
  mapping:
    entity_type_bundles:
      type: sequence
      label: Entity type bundles
      sequence:
        type: string
        label: Entity type bundle concatenation
    temporary_uri:
      type: uri
      label: Entity temporary export file URI
    delete_exported_file:
      type: boolean
      label: Entity export file delete flag
    entity_bundle_configuration:
      type: sequence
      label: Entity bundle configurations
      sequence:
        type: sequence
        label: Entity configuration
        sequence:
          type: mapping
          label: Bundle configuration
          mapping:
            display_mode:
              type: string
              label: Export entity bundle display mode

  entity.view_display.*.third_party.entity_content_export:
    type: mapping
    label: 'Entity content export third-party setting'
    mapping:
      base_fields:
        type: sequence
        label: 'The settings base fields to display'
        sequence:
          type: string
          label: 'The settings base field name'
      components:
        type: mapping
        label: 'The settings components'
        mapping:
          type: sequence
          label: 'The settings component field name'
          sequence:
            type: mapping
            label: 'The settings component information'
            mapping:
              name:
                type: string
                label: 'The settings component rendered name'
              render:
                type: string
                label: 'The settings component rendered type'
